const progress=document.querySelector('.progress');
window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max?scrollY/max*100:0)+'%'},{passive:true});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -45px'});
document.querySelectorAll('.reveal').forEach((el,i)=>{el.style.transitionDelay=Math.min((i%6)*65,260)+'ms';observer.observe(el)});
const counters=document.querySelectorAll('[data-count]');
const counterObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting&&!entry.target.dataset.done){entry.target.dataset.done='1';const target=Number(entry.target.dataset.count);let start=0;const startTime=performance.now();const duration=950;const tick=now=>{const p=Math.min((now-startTime)/duration,1);const eased=1-Math.pow(1-p,3);entry.target.textContent=Math.round(start+(target-start)*eased);if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);counterObserver.unobserve(entry.target)}}),{threshold:.65});counters.forEach(x=>counterObserver.observe(x));
const menu=document.querySelector('.menu-btn'),mobile=document.querySelector('.mobile-nav');menu.addEventListener('click',()=>mobile.classList.toggle('open'));mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mobile.classList.remove('open')));
const processSteps=[...document.querySelectorAll('.process-step')],processLine=document.querySelector('.process-progress span');
const processObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){processSteps.forEach(s=>s.classList.remove('active'));entry.target.classList.add('active');const i=processSteps.indexOf(entry.target);processLine.style.height=((i+1)/processSteps.length*100)+'%'}}),{threshold:.6});processSteps.forEach(s=>processObserver.observe(s));
const cases={
banking:{k:'CASE 01 · ENTERPRISE BANKING',t:'Digital Payments & Banking Integrations',s:'Enterprise delivery programs for a leading Latin American financial institution focused on digital payments and banking integrations.',c:'Multiple workstreams, global stakeholders, delivery priorities and dependencies needed to move together while maintaining visibility and quality.',r:'Technical Project Manager — collaborated with global stakeholders, architects and business teams and coordinated delivery priorities, requirements, dependencies and releases.',a:'Defined roadmaps and release plans, drove Agile execution, coordinated dependencies, managed risks and escalations, and maintained structured stakeholder communication and delivery governance.',e:'Oversaw sprint planning, release coordination, issue resolution, project financials, utilization and delivery KPIs across managed workstreams.',o:'All major milestones were delivered on time and within approved budget, achieving 100% stakeholder satisfaction and a 35% improvement in client satisfaction. Critical banking integration modules were delivered with zero major post-release defects.'},
pmo:{k:'CASE 02 · PMO / DELIVERY GOVERNANCE',t:'PMO Frameworks & Delivery Visibility',s:'Governance, reporting and operating structures established across multi-stream enterprise technology initiatives at Valethi Technologies.',c:'Multiple delivery streams across finance systems, websites, mobile applications, analytics and automation needed consistent planning, ownership, visibility and execution discipline.',r:'Associate Project Manager — owned project lifecycle management, planning, commercial activities, governance design, execution tracking and stakeholder communication.',a:'Established PMO frameworks, governance templates, reporting mechanisms and standardized operating procedures; combined KPI tracking, dependency coordination, resource planning and structured reporting.',e:'Managed distributed cross-functional teams across requirements, feasibility, planning, execution, risks, dependencies, escalations and releases while supporting budgeting, effort estimation and commercial proposals.',o:'Structured planning and workflow improvements reduced overall delivery cycle time by 35%. Proactive process improvements reduced escalations by 40% and improved delivery predictability and stakeholder communication.'},
ai:{k:'CASE 03 · AI / PRODUCT DELIVERY',t:'AI Tools & Product Delivery',s:'AI-assisted operational tools and an AI-powered product initiative delivered through structured product and project execution.',c:'Operational processes required clearer ownership, SLAs and milestone tracking, while emerging AI capabilities created an opportunity to build practical internal tools.',r:'Project / delivery lead — translated operational needs into scoped work, coordinated the AI-assisted build and led delivery from ideation through execution.',a:'Used OpenAI APIs, Claude APIs and prompt engineering alongside structured scoping, coordination and execution practices.',e:'Designed and developed a full-stack Onboarding Tracker and Hiring Process Matrix with defined SLAs and milestone ownership, and led an AI-powered product initiative from ideation and scoping through execution.',o:'Delivered AI-assisted operational tools and an AI-powered product initiative. The resume does not specify a quantified business outcome for this work, so no additional metric is presented.'}
};
const modal=document.querySelector('.case-modal');const set=(id,v)=>document.getElementById(id).textContent=v;
document.querySelectorAll('.case-btn').forEach(btn=>btn.addEventListener('click',()=>{const d=cases[btn.closest('.case').dataset.case];set('modal-kicker',d.k);set('modal-title',d.t);set('modal-summary',d.s);set('modal-context',d.c);set('modal-challenge',d.c);set('modal-role',d.r);set('modal-approach',d.a);set('modal-execution',d.e);set('modal-outcome',d.o);modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}));
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
document.querySelector('.modal-close').addEventListener('click',closeModal);document.querySelector('.modal-backdrop').addEventListener('click',closeModal);window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
